server:
  port: 0

spring:
  application:
    name: iiiiii-accbook-service

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ENC(toah0owEKfDtW+QCVdZvw3S1shWBm6EbJkGpFxG3vUi3a+laHQyAaJOyTnuOh0Ll)
    username: ENC(zgZMwT+puERfQ2nHlUZA1w==)
    password: ENC(cGQqlfzdn+lEdgIrsjm2ew==)

  # jpa
  jpa:
    generate-ddl: false
    show-sql: true
    database: mysql
    properties:
      hibernate:
        '[format_sql]': true  # change to pretty SQL text

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

jasypt:
  encryptor:
    password: 12345678
    algorithm: PBEWithMD5AndDES