server:
  port: 0

spring:
  application:
    name: iiiiii-member-service

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ENC(toah0owEKfDtW+QCVdZvw3S1shWBm6EbJkGpFxG3vUi3a+laHQyAaJOyTnuOh0Ll)
    username: ENC(zgZMwT+puERfQ2nHlUZA1w==)
    password: ENC(cGQqlfzdn+lEdgIrsjm2ew==)

  jpa:
    generate-ddl: false
    show-sql: true
    database: mysql
    properties:
      hibernate:
        '[format_sql]': true  # change to pretty SQL text


eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

# token config 설정
token:

  # 만료시간 설정(ms 단위)(현재 12시간)
  expiration_time: 43200000

  # secret 키 생성
  secret: ENC(ky8shvJwQboFih4cWJocMZqICgX0a54ZuBzY/LoUv1mW1tidWiYVQEEek4DjwJwAgabg9iX3A3hm0rblePMTweUzatufjd+4DNkIMtPFnPvLYzLtsDf7Z3rW1SVFSSX3DVvR5JcGrrI=)

logging:
  level:
    root: INFO
    com.iiiiii.accbooksecurity: DEBUG
  console:
    enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

jasypt:
  encryptor:
    password: 123456
    algorithm: PBEWithMD5AndDES
